# Generated by Django 4.1.3 on 2022-11-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_duedate_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='duedate',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
    ]
