# Generated by Django 4.1.3 on 2022-11-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_todo_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
